<a href="https://colab.research.google.com/github/GerryMasaka/ForwardPropagation/blob/main/ForwardProp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd #dataset library
import numpy as np #linear algebra library

In [ ]:
from numpy import array
from sklearn.preprocessing import Normalizer
from keras.activations import sigmoid
from keras.losses import mse
from numpy.random import uniform,normal

In [ ]:
batch_size=2

In [ ]:
data_dict={'Day 1':[30,40,50,20,15,60],'Day 2':[40,50,20,15,60,70],'Day 3':[50,20,15,60,70,50], 'Target':[20,15,60,70,50,40]}

In [ ]:
data=pd.DataFrame(data_dict)

In [ ]:
data

Day 1  Day 2  Day 3  Target
0     30     40     50      20
1     40     50     20      15
2     50     20     15      60
3     20     15     60      70
4     15     60     70      50
5     60     70     50      40

In [ ]:
X=data.drop('Target',axis=1)
y=data['Target']

In [ ]:
X_trans=Normalizer(norm='max').fit_transform(X)

In [ ]:
np.reshape(array(y),(1,-1))

array([[20, 15, 60, 70, 50, 40]])

In [ ]:
y=Normalizer().fit_transform(np.reshape(array(y),(1,-1)))

In [ ]:
y

array([[0.17391304, 0.13043478, 0.52173913, 0.60869565, 0.43478261,
        0.34782609]])

In [ ]:
X_trans

array([[0.42426407, 0.56568542, 0.70710678],
       [0.59628479, 0.74535599, 0.2981424 ],
       [0.89442719, 0.35777088, 0.26832816],
       [0.30769231, 0.23076923, 0.92307692],
       [0.16058632, 0.64234527, 0.74940282],
       [0.57207755, 0.66742381, 0.47673129]])

ANN Model From Scratch

In [ ]:
"""weight_1=array([[.2,.1],[.3,.1],[.2"

In [ ]:
weight_1=array([[.2,.1],[.3,.1],[.2,.1]])
weight_2=array([[.5],[.1]])

In [ ]:
X=X_trans

In [ ]:
output_1=X[0]@weight_1
output_1

array([0.3959798 , 0.16970563])

In [ ]:
act_output_1=sigmoid(output_1).numpy()
act_output_1

array([0.59772138, 0.54232488])

In [ ]:
final_output=act_output_1@weight_2
final_output

array([0.35309318])

In [ ]:
y_true=y[0][0:batch_size]
y_pred=final_output.T[0]

In [ ]:
y_true

array([0.17391304, 0.13043478])

In [ ]:
y_pred

0.3530931781838482

computing mean squared error

In [ ]:
mse(y_true,y_pred).numpy()

0.04084114089660677